openapi: 3.0.1
info:
  title: '@jupiterone/graph-microsoft-teams'
  description: A JupiterOne Integration for ingesting data of the Microsoft Teams
  x-cortex-git:
    github:
      repository: JupiterOne/graph-microsoft-teams
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-microsoft-teams'
